# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test1.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1011, 670)
        Form.setMouseTracking(False)
        self.m_ButtonTrue = QtWidgets.QPushButton(Form)
        self.m_ButtonTrue.setGeometry(QtCore.QRect(330, 280, 71, 31))
        self.m_ButtonTrue.setObjectName("m_ButtonTrue")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(280, 190, 271, 22))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.m_UsernameLabel = QtWidgets.QLabel(self.layoutWidget)
        self.m_UsernameLabel.setObjectName("m_UsernameLabel")
        self.horizontalLayout.addWidget(self.m_UsernameLabel)
        self.m_UserName = QtWidgets.QLineEdit(self.layoutWidget)
        self.m_UserName.setObjectName("m_UserName")
        self.horizontalLayout.addWidget(self.m_UserName)
        self.layoutWidget1 = QtWidgets.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(290, 230, 261, 22))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.m_Pwd = QtWidgets.QLineEdit(self.layoutWidget1)
        self.m_Pwd.setObjectName("m_Pwd")
        self.horizontalLayout_2.addWidget(self.m_Pwd)
        self.m_ButtonFalse = QtWidgets.QToolButton(Form)
        self.m_ButtonFalse.setGeometry(QtCore.QRect(420, 280, 71, 31))
        self.m_ButtonFalse.setObjectName("m_ButtonFalse")
        self.m_Button1 = QtWidgets.QPushButton(Form)
        self.m_Button1.setGeometry(QtCore.QRect(650, 150, 61, 31))
        self.m_Button1.setObjectName("m_Button1")
        self.m_Button2 = QtWidgets.QPushButton(Form)
        self.m_Button2.setGeometry(QtCore.QRect(650, 200, 61, 31))
        self.m_Button2.setObjectName("m_Button2")
        self.m_Button3 = QtWidgets.QPushButton(Form)
        self.m_Button3.setGeometry(QtCore.QRect(650, 240, 61, 31))
        self.m_Button3.setObjectName("m_Button3")
        self.m_Button4 = QtWidgets.QPushButton(Form)
        self.m_Button4.setGeometry(QtCore.QRect(650, 300, 61, 31))
        self.m_Button4.setObjectName("m_Button4")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.m_ButtonTrue.setText(_translate("Form", "确定"))
        self.m_UsernameLabel.setText(_translate("Form", "用户名："))
        self.label_2.setText(_translate("Form", "密码："))
        self.m_ButtonFalse.setText(_translate("Form", "警告框"))
        self.m_Button1.setText(_translate("Form", "询问框"))
        self.m_Button2.setText(_translate("Form", "错误框"))
        self.m_Button3.setText(_translate("Form", "提示框"))
        self.m_Button4.setText(_translate("Form", "button4"))
